import React, { useState, useEffect } from 'react';
import { MaintenanceJobCard } from '../components/maintenance/MaintenanceJobCard';
import { JobFilters } from '../components/maintenance/JobFilters';
import { EmptyState } from '../components/common/EmptyState';
import { getMaintenancePriorities } from '../services/api';
import { Wrench, Award, RefreshCw, AlertTriangle, LayoutGrid, List } from 'lucide-react';
import { getDepartmentInfo, PRIORITY_CONFIG } from '../utils/departmentConfig';
import { Badge } from '../components/common/Badge';

export const Maintenance = ({ planDate = '2026-09-10' }) => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [jobs, setJobs] = useState([]);

  // Filters
  const [department, setDepartment] = useState('');
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [viewMode, setViewMode] = useState('grid'); // 'grid' | 'table'

  const loadPriorities = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await getMaintenancePriorities({
        reference_date: planDate,
        department: department || undefined
      });
      setJobs(data);
    } catch (err) {
      setError(err.message || 'Failed to load maintenance priorities');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPriorities();
  }, [planDate, department]);

  // Client-side filtering for status and search query
  const filteredJobs = jobs.filter((j) => {
    if (status && j.status !== status) return false;
    if (search) {
      const q = search.toLowerCase();
      const code = (j.job_code || '').toLowerCase();
      const desc = (j.description || '').toLowerCase();
      const asset = (j.asset_code || '').toLowerCase();
      const sec = (j.section_code || '').toLowerCase();
      if (!code.includes(q) && !desc.includes(q) && !asset.includes(q) && !sec.includes(q)) {
        return false;
      }
    }
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Title & Stats */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100 tracking-tight flex items-center gap-2">
            <Award className="w-5 h-5 text-amber-400" />
            Maintenance Priorities Directory
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Deterministic multi-attribute ranking generated by the SIH26027 Priority Engine
          </p>
        </div>

        <div className="flex items-center gap-2">
          {/* View mode toggle */}
          <div className="flex rounded-lg bg-slate-900 border border-slate-800 p-0.5">
            <button
              onClick={() => setViewMode('grid')}
              className={`p-1.5 rounded text-xs transition-colors ${
                viewMode === 'grid' ? 'bg-slate-800 text-amber-400' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Grid Card View"
            >
              <LayoutGrid className="w-4 h-4" />
            </button>
            <button
              onClick={() => setViewMode('table')}
              className={`p-1.5 rounded text-xs transition-colors ${
                viewMode === 'table' ? 'bg-slate-800 text-amber-400' : 'text-slate-400 hover:text-slate-200'
              }`}
              title="Table View"
            >
              <List className="w-4 h-4" />
            </button>
          </div>

          <button
            onClick={loadPriorities}
            disabled={loading}
            className="p-2 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 transition-colors disabled:opacity-50"
            title="Refresh priority list"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin text-amber-400' : ''}`} />
          </button>
        </div>
      </div>

      {/* Filter Toolbar */}
      <JobFilters
        department={department}
        setDepartment={setDepartment}
        status={status}
        setStatus={setStatus}
        search={search}
        setSearch={setSearch}
      />

      {/* Error notification */}
      {error && (
        <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Jobs View: Grid vs Table */}
      {filteredJobs.length === 0 ? (
        <EmptyState
          icon={Wrench}
          title="No Maintenance Jobs Found"
          description="No maintenance work orders match the selected department or status filters."
          action={
            <button
              onClick={() => {
                setDepartment('');
                setStatus('');
                setSearch('');
              }}
              className="px-3.5 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium"
            >
              Clear Filters
            </button>
          }
        />
      ) : viewMode === 'grid' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredJobs.map((job) => (
            <MaintenanceJobCard key={job.job_id || job.id} job={job} />
          ))}
        </div>
      ) : (
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-lg">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-slate-950/80 border-b border-slate-800 text-slate-400 text-[11px]">
                <tr>
                  <th className="py-3 px-3">Job Code</th>
                  <th className="py-3 px-3">Department</th>
                  <th className="py-3 px-3">Asset</th>
                  <th className="py-3 px-3">Section</th>
                  <th className="py-3 px-3 text-right">Priority</th>
                  <th className="py-3 px-3 text-center">Crit</th>
                  <th className="py-3 px-3 text-center">Urg</th>
                  <th className="py-3 px-3">Overdue</th>
                  <th className="py-3 px-3">Deadline</th>
                  <th className="py-3 px-3 text-right">Duration</th>
                  <th className="py-3 px-3">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {filteredJobs.map((j) => {
                  const dept = getDepartmentInfo(j.department);
                  const pInfo = PRIORITY_CONFIG[j.priority_level] || PRIORITY_CONFIG.MEDIUM;
                  return (
                    <tr key={j.job_id || j.id} className="hover:bg-slate-800/40">
                      <td className="py-2.5 px-3 font-bold text-slate-200">
                        {j.job_code}
                      </td>
                      <td className="py-2.5 px-3">
                        <span className={`px-2 py-0.5 rounded text-[10px] border ${dept.badgeColor}`}>
                          {dept.shortName}
                        </span>
                      </td>
                      <td className="py-2.5 px-3 text-slate-300">
                        {j.asset_code || 'Track'}
                      </td>
                      <td className="py-2.5 px-3 text-slate-400">
                        {j.section_code || '--'}
                      </td>
                      <td className="py-2.5 px-3 text-right font-bold">
                        <span className={`px-2 py-0.5 rounded border text-[11px] ${pInfo.badgeColor}`}>
                          {typeof j.priority_score === 'number' ? j.priority_score.toFixed(1) : j.priority_score}
                        </span>
                      </td>
                      <td className="py-2.5 px-3 text-center text-amber-400">
                        {j.criticality || '--'}
                      </td>
                      <td className="py-2.5 px-3 text-center text-slate-300">
                        {j.urgency || '--'}
                      </td>
                      <td className="py-2.5 px-3">
                        {j.overdue_days > 0 ? (
                          <span className="text-rose-400 font-bold">+{j.overdue_days}d</span>
                        ) : (
                          <span className="text-slate-600">0d</span>
                        )}
                      </td>
                      <td className="py-2.5 px-3 text-slate-400 text-[11px]">
                        {j.deadline ? j.deadline.slice(0, 10) : 'Open'}
                      </td>
                      <td className="py-2.5 px-3 text-right text-slate-300">
                        {j.duration_minutes || j.estimated_duration_minutes || 60}m
                      </td>
                      <td className="py-2.5 px-3">
                        <Badge variant={j.status?.toLowerCase() || 'default'} size="xs">
                          {j.status || 'PENDING'}
                        </Badge>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};
